<a href="https://colab.research.google.com/github/kunalyadav93/Community-Resource-Index-DFW/blob/master/Data_Preperation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## The code below prepares the dataset that contains below indicators
#### 1. Employment Rate
#### 2. Commute Duration
#### 3. Family below poverty level
#### 4. Median household income
#### 5. Gini Index
#### 6. House Ownership Rate
#### 7. Public Assistance
#### 8. SNAP

Files were extracted from the data.census.gov website.

In [0]:
import numpy as np
import pandas as pd

### 1. Employment Rate

Table Name : B23001

URL : https://data.census.gov/cedsci/table?q=B23001%3A%20SEX%20BY%20AGE%20BY%20EMPLOYMENT%20STATUS%20FOR%20THE%20POPULATION%2016%20YEARS%20AND%20OVER&tid=ACSDT5Y2017.B23001&hidePreview=true&tp=true&vintage=2017&g=0500000US48085.140000,48113.140000,48121.140000,48439.140000&t=Employment%20and%20Labor%20Force%20Status&moe=false

In [0]:
employment= pd.read_csv("ACSDT5Y2018.B23001_data_with_overlays_2020-04-14T132501.csv",header=1)

#### Removing error columns

In [0]:
cols=[i for i in employment.columns if "Error" not in i]
employment=employment[cols]
employment.head(5)

,id,Geographic Area Name,Estimate!!Total,Estimate!!Total!!Male,Estimate!!Total!!Male!!16 to 19 years,Estimate!!Total!!Male!!16 to 19 years!!In labor force,Estimate!!Total!!Male!!16 to 19 years!!In labor force!!In Armed Forces,Estimate!!Total!!Male!!16 to 19 years!!In labor force!!Civilian,Estimate!!Total!!Male!!16 to 19 years!!In labor force!!Civilian!!Employed,Estimate!!Total!!Male!!16 to 19 years!!In labor force!!Civilian!!Unemployed,...,Estimate!!Total!!Female!!70 to 74 years,Estimate!!Total!!Female!!70 to 74 years!!In labor force,Estimate!!Total!!Female!!70 to 74 years!!In labor force!!Employed,Estimate!!Total!!Female!!70 to 74 years!!In labor force!!Unemployed,Estimate!!Total!!Female!!70 to 74 years!!Not in labor force,Estimate!!Total!!Female!!75 years and over,Estimate!!Total!!Female!!75 years and over!!In labor force,Estimate!!Total!!Female!!75 years and over!!In labor force!!Employed,Estimate!!Total!!Female!!75 years and over!!In labor force!!Unemployed,Estimate!!Total!!Female!!75 years and over!!Not in labor force
0,1400000US48085031625,"Census Tract 316.25, Collin County, Texas",3769,1780,22,11,0,11,11,0,...,191,9,9,0,182,168,10,10,0,158
1,1400000US48085031633,"Census Tract 316.33, Collin County, Texas",3453,1676,87,10,0,10,10,0,...,135,33,33,0,102,64,0,0,0,64
2,1400000US48085031636,"Census Tract 316.36, Collin County, Texas",5929,2598,202,39,0,39,39,0,...,173,81,61,20,92,242,18,18,0,224
3,1400000US48085032008,"Census Tract 320.08, Collin County, Texas",3818,1885,110,49,0,49,49,0,...,75,37,37,0,38,163,28,28,0,135
4,1400000US48085031505,"Census Tract 315.05, Collin County, Texas",6361,3215,319,141,0,141,141,0,...,171,22,22,0,149,114,0,0,0,114

#### Creating the column Employment Rate

In [0]:
employment['In_labor_force(population)']=employment.loc[:,employment.columns.str.endswith("In labor force")].sum(axis=1)
employment["Employment_rate(%)(population)"]=employment['In_labor_force(population)']/employment['Estimate!!Total']*100

In [0]:
employment=employment[['id','Geographic Area Name','Estimate!!Total',
            'In_labor_force(population)','Employment_rate(%)(population)'
           ]].rename(columns={'Estimate!!Total':'Total_Population'})

In [0]:
employment

,id,Geographic Area Name,Total_Population,In_labor_force(population),Employment_rate(%)(population)
0,1400000US48085031625,"Census Tract 316.25, Collin County, Texas",3769,2497,66.250995
1,1400000US48085031633,"Census Tract 316.33, Collin County, Texas",3453,2504,72.516652
2,1400000US48085031636,"Census Tract 316.36, Collin County, Texas",5929,3748,63.214707
3,1400000US48085032008,"Census Tract 320.08, Collin County, Texas",3818,2745,71.896281
4,1400000US48085031505,"Census Tract 315.05, Collin County, Texas",6361,4813,75.664204
...,...,...,...,...,...
1170,1400000US48439114006,"Census Tract 1140.06, Tarrant County, Texas",5461,3851,70.518220
1171,1400000US48439101301,"Census Tract 1013.01, Tarrant County, Texas",3940,2310,58.629442
1172,1400000US48439104503,"Census Tract 1045.03, Tarrant County, Texas",2085,1191,57.122302
1173,1400000US48439106101,"Census Tract 1061.01, Tarrant County, Texas",1236,675,54.611650
1174,1400000US48439100502,"Census Tract 1005.02, Tarrant County, Texas",5758,3861,67.054533

### 2. Commute Duration
Table : B08303

In [0]:
commute_df=pd.read_csv("ACSDT5Y2018.B08303_data_with_overlays_2020-04-14T130800.csv",header=1)

#### Removing error columns

In [0]:
cols=[i for i in commute_df.columns if "Error" not in i]
commute_df=commute_df[cols]
commute_df.head(5)

,id,Geographic Area Name,Estimate!!Total,Estimate!!Total!!Less than 5 minutes,Estimate!!Total!!5 to 9 minutes,Estimate!!Total!!10 to 14 minutes,Estimate!!Total!!15 to 19 minutes,Estimate!!Total!!20 to 24 minutes,Estimate!!Total!!25 to 29 minutes,Estimate!!Total!!30 to 34 minutes,Estimate!!Total!!35 to 39 minutes,Estimate!!Total!!40 to 44 minutes,Estimate!!Total!!45 to 59 minutes,Estimate!!Total!!60 to 89 minutes,Estimate!!Total!!90 or more minutes
0,1400000US48085031625,"Census Tract 316.25, Collin County, Texas",2146,38,142,156,449,394,217,293,154,48,146,94,15
1,1400000US48085031633,"Census Tract 316.33, Collin County, Texas",2109,0,52,177,339,615,171,362,66,113,88,100,26
2,1400000US48085031636,"Census Tract 316.36, Collin County, Texas",3225,19,48,341,394,772,69,548,180,153,391,243,67
3,1400000US48085032008,"Census Tract 320.08, Collin County, Texas",2497,10,362,245,240,312,127,566,91,121,265,149,9
4,1400000US48085031505,"Census Tract 315.05, Collin County, Texas",4322,53,509,311,769,626,302,571,209,196,478,285,13

#### Creating the column Commute Duration 60+ minutes

In [0]:
commute_df["Commute_Duration_60+(pcw)"]=commute_df['Estimate!!Total!!60 to 89 minutes']+commute_df['Estimate!!Total!!90 or more minutes']
commute_df['% Population_Work_Commute_Duration_60+(pcw)']=commute_df["Commute_Duration_60+(pcw)"]/commute_df['Estimate!!Total']*100

#### Creating the column Commute Duration 90+ minutes

In [0]:
commute_df['% Population_Work_Commute_Duration_90+(pcw)']=commute_df["Estimate!!Total!!90 or more minutes"]/commute_df['Estimate!!Total']*100

In [0]:
commute_df=commute_df[['id','Geographic Area Name','Estimate!!Total','Commute_Duration_60+(pcw)',
            '% Population_Work_Commute_Duration_60+(pcw)','Estimate!!Total!!90 or more minutes',
            '% Population_Work_Commute_Duration_90+(pcw)'
           ]].rename(columns={'Estimate!!Total':'Population_commuting_to_work(pcw)',
                              'Estimate!!Total!!90 or more minutes':'Commute_Duration_90+(pcw)'})

In [0]:
commute_df

,id,Geographic Area Name,Population_commuting_to_work(pcw),Commute_Duration_60+(pcw),% Population_Work_Commute_Duration_60+(pcw),Commute_Duration_90+(pcw),% Population_Work_Commute_Duration_90+(pcw)
0,1400000US48085031625,"Census Tract 316.25, Collin County, Texas",2146,109,5.079217,15,0.698975
1,1400000US48085031633,"Census Tract 316.33, Collin County, Texas",2109,126,5.974395,26,1.232812
2,1400000US48085031636,"Census Tract 316.36, Collin County, Texas",3225,310,9.612403,67,2.077519
3,1400000US48085032008,"Census Tract 320.08, Collin County, Texas",2497,158,6.327593,9,0.360433
4,1400000US48085031505,"Census Tract 315.05, Collin County, Texas",4322,298,6.894956,13,0.300787
...,...,...,...,...,...,...,...
1170,1400000US48439114006,"Census Tract 1140.06, Tarrant County, Texas",3475,270,7.769784,83,2.388489
1171,1400000US48439101301,"Census Tract 1013.01, Tarrant County, Texas",2085,79,3.788969,34,1.630695
1172,1400000US48439104503,"Census Tract 1045.03, Tarrant County, Texas",1034,127,12.282398,36,3.481625
1173,1400000US48439106101,"Census Tract 1061.01, Tarrant County, Texas",575,54,9.391304,13,2.260870
1174,1400000US48439100502,"Census Tract 1005.02, Tarrant County, Texas",3444,269,7.810685,138,4.006969

### 3. Family below poverty level
Table: B17010

In [0]:
fam_df=pd.read_csv("ACSDT5Y2018.B17010_data_with_overlays_2020-04-14T132004.csv",header=1)

#### Removing error columns

In [0]:
cols=[i for i in fam_df.columns if "Error" not in i]
fam_df=fam_df[cols]
fam_df.head(5)

,id,Geographic Area Name,Estimate!!Total,Estimate!!Total!!Income in the past 12 months below poverty level,Estimate!!Total!!Income in the past 12 months below poverty level!!Married-couple family,Estimate!!Total!!Income in the past 12 months below poverty level!!Married-couple family!!With related children of the householder under 18 years,Estimate!!Total!!Income in the past 12 months below poverty level!!Married-couple family!!With related children of the householder under 18 years!!Under 5 years only,Estimate!!Total!!Income in the past 12 months below poverty level!!Married-couple family!!With related children of the householder under 18 years!!Under 5 years and 5 to 17 years,Estimate!!Total!!Income in the past 12 months below poverty level!!Married-couple family!!With related children of the householder under 18 years!!5 to 17 years only,Estimate!!Total!!Income in the past 12 months below poverty level!!Married-couple family!!No related children of the householder under 18 years,...,"Estimate!!Total!!Income in the past 12 months at or above poverty level!!Other family!!Male householder, no wife present!!With related children of the householder under 18 years!!Under 5 years only","Estimate!!Total!!Income in the past 12 months at or above poverty level!!Other family!!Male householder, no wife present!!With related children of the householder under 18 years!!Under 5 years and 5 to 17 years","Estimate!!Total!!Income in the past 12 months at or above poverty level!!Other family!!Male householder, no wife present!!With related children of the householder under 18 years!!5 to 17 years only","Estimate!!Total!!Income in the past 12 months at or above poverty level!!Other family!!Male householder, no wife present!!No related children of the householder under 18 years","Estimate!!Total!!Income in the past 12 months at or above poverty level!!Other family!!Female householder, no husband present","Estimate!!Total!!Income in the past 12 months at or above poverty level!!Other family!!Female householder, no husband present!!With related children of the householder under 18 years","Estimate!!Total!!Income in the past 12 months at or above poverty level!!Other family!!Female householder, no husband present!!With related children of the householder under 18 years!!Under 5 years only","Estimate!!Total!!Income in the past 12 months at or above poverty level!!Other family!!Female householder, no husband present!!With related children of the householder under 18 years!!Under 5 years and 5 to 17 years","Estimate!!Total!!Income in the past 12 months at or above poverty level!!Other family!!Female householder, no husband present!!With related children of the householder under 18 years!!5 to 17 years only","Estimate!!Total!!Income in the past 12 months at or above poverty level!!Other family!!Female householder, no husband present!!No related children of the householder under 18 years"
0,1400000US48085031625,"Census Tract 316.25, Collin County, Texas",1389,72,67,0,0,0,0,67,...,11,0,29,20,227,110,0,0,110,117
1,1400000US48085031633,"Census Tract 316.33, Collin County, Texas",1112,4,4,4,0,0,4,0,...,20,0,36,36,93,30,0,0,30,63
2,1400000US48085031636,"Census Tract 316.36, Collin County, Texas",2023,12,12,0,0,0,0,12,...,0,0,0,45,340,135,0,0,135,205
3,1400000US48085032008,"Census Tract 320.08, Collin County, Texas",1189,67,26,0,0,0,0,26,...,6,0,9,57,112,68,10,0,58,44
4,1400000US48085031505,"Census Tract 315.05, Collin County, Texas",2298,107,76,46,0,16,30,30,...,0,0,0,50,187,90,0,0,90,97

#### Creating column : Families below poverty level

In [0]:
fam_df['% family_below_poverty_level(family)']=fam_df['Estimate!!Total!!Income in the past 12 months below poverty level']/fam_df['Estimate!!Total']*100

#### Creating column : Single-Headed families below poverty level

In [0]:
fam_df["% Single_headed_family_below_poverty_level(family)"]=fam_df['Estimate!!Total!!Income in the past 12 months below poverty level!!Other family']/fam_df['Estimate!!Total']*100

In [0]:
fam_df=fam_df[['id','Geographic Area Name','Estimate!!Total',
        '% family_below_poverty_level(family)',
        '% Single_headed_family_below_poverty_level(family)'
       ]].rename(columns={'Estimate!!Total':'Total_family'})

In [0]:
fam_df

,id,Geographic Area Name,Total_family,% family_below_poverty_level(family),% Single_headed_family_below_poverty_level(family)
0,1400000US48085031625,"Census Tract 316.25, Collin County, Texas",1389,5.183585,0.359971
1,1400000US48085031633,"Census Tract 316.33, Collin County, Texas",1112,0.359712,0.000000
2,1400000US48085031636,"Census Tract 316.36, Collin County, Texas",2023,0.593178,0.000000
3,1400000US48085032008,"Census Tract 320.08, Collin County, Texas",1189,5.634987,3.448276
4,1400000US48085031505,"Census Tract 315.05, Collin County, Texas",2298,4.656223,1.348999
...,...,...,...,...,...
1170,1400000US48439114006,"Census Tract 1140.06, Tarrant County, Texas",1878,8.093717,3.674121
1171,1400000US48439101301,"Census Tract 1013.01, Tarrant County, Texas",1157,18.755402,14.174589
1172,1400000US48439104503,"Census Tract 1045.03, Tarrant County, Texas",658,20.060790,11.702128
1173,1400000US48439106101,"Census Tract 1061.01, Tarrant County, Texas",409,20.048900,16.625917
1174,1400000US48439100502,"Census Tract 1005.02, Tarrant County, Texas",1850,18.108108,7.405405

### 4. Median Household Income
Table B19013

In [0]:
median_household=pd.read_csv("ACSDT5Y2018.B19013_data_with_overlays_2020-04-18T131847.csv",header=1)

In [0]:
median_household=median_household[['id','Geographic Area Name',
                  "Estimate!!Median household income in the past 12 months (in 2018 inflation-adjusted dollars)"
                 ]].rename(columns={'Estimate!!Median household income in the past 12 months (in 2018 inflation-adjusted dollars)':'Median_household_income'})

In [0]:
median_household

,id,Geographic Area Name,Median_household_income
0,1400000US48085031625,"Census Tract 316.25, Collin County, Texas",101250
1,1400000US48085031633,"Census Tract 316.33, Collin County, Texas",96188
2,1400000US48085031636,"Census Tract 316.36, Collin County, Texas",101466
3,1400000US48085032008,"Census Tract 320.08, Collin County, Texas",86615
4,1400000US48085031505,"Census Tract 315.05, Collin County, Texas",122575
...,...,...,...
1170,1400000US48439114006,"Census Tract 1140.06, Tarrant County, Texas",76426
1171,1400000US48439101301,"Census Tract 1013.01, Tarrant County, Texas",38844
1172,1400000US48439104503,"Census Tract 1045.03, Tarrant County, Texas",42386
1173,1400000US48439106101,"Census Tract 1061.01, Tarrant County, Texas",37063
1174,1400000US48439100502,"Census Tract 1005.02, Tarrant County, Texas",42066

### 5. Gini Index
Table B19083

In [0]:
gini=pd.read_csv("ACSDT5Y2018.B19083_data_with_overlays_2020-04-19T053640.csv",header=1)

In [0]:
gini=gini[['id','Geographic Area Name',"Estimate!!Gini Index"]].rename(columns={'Estimate!!Gini Index':'gini_index'})

In [0]:
gini

,id,Geographic Area Name,gini_index
0,1400000US48085031625,"Census Tract 316.25, Collin County, Texas",0.4158
1,1400000US48085031633,"Census Tract 316.33, Collin County, Texas",0.3333
2,1400000US48085031636,"Census Tract 316.36, Collin County, Texas",0.4336
3,1400000US48085032008,"Census Tract 320.08, Collin County, Texas",0.3880
4,1400000US48085031505,"Census Tract 315.05, Collin County, Texas",0.3673
...,...,...,...
1170,1400000US48439114006,"Census Tract 1140.06, Tarrant County, Texas",0.3714
1171,1400000US48439101301,"Census Tract 1013.01, Tarrant County, Texas",0.4664
1172,1400000US48439104503,"Census Tract 1045.03, Tarrant County, Texas",0.3995
1173,1400000US48439106101,"Census Tract 1061.01, Tarrant County, Texas",0.3938
1174,1400000US48439100502,"Census Tract 1005.02, Tarrant County, Texas",0.3810

### 6. House ownership rate
Table DP04

In [0]:
house_ownership=pd.read_csv("ACSDP5Y2018.DP04_data_with_overlays_2020-04-19T054110.csv",header=1)

#### Removing error column

In [0]:
cols=[i for i in house_ownership.columns if "Error" not in i]
house_ownership=house_ownership[cols]
house_ownership.head(5)

,id,Geographic Area Name,Estimate!!HOUSING OCCUPANCY!!Total housing units,Percent Estimate!!HOUSING OCCUPANCY!!Total housing units,Estimate!!HOUSING OCCUPANCY!!Total housing units!!Occupied housing units,Percent Estimate!!HOUSING OCCUPANCY!!Total housing units!!Occupied housing units,Estimate!!HOUSING OCCUPANCY!!Total housing units!!Vacant housing units,Percent Estimate!!HOUSING OCCUPANCY!!Total housing units!!Vacant housing units,Estimate!!HOUSING OCCUPANCY!!Total housing units!!Homeowner vacancy rate,Percent Estimate!!HOUSING OCCUPANCY!!Total housing units!!Homeowner vacancy rate,...,Estimate!!GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME (GRAPI)!!Occupied units paying rent (excluding units where GRAPI cannot be computed)!!20.0 to 24.9 percent,Percent Estimate!!GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME (GRAPI)!!Occupied units paying rent (excluding units where GRAPI cannot be computed)!!20.0 to 24.9 percent,Estimate!!GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME (GRAPI)!!Occupied units paying rent (excluding units where GRAPI cannot be computed)!!25.0 to 29.9 percent,Percent Estimate!!GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME (GRAPI)!!Occupied units paying rent (excluding units where GRAPI cannot be computed)!!25.0 to 29.9 percent,Estimate!!GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME (GRAPI)!!Occupied units paying rent (excluding units where GRAPI cannot be computed)!!30.0 to 34.9 percent,Percent Estimate!!GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME (GRAPI)!!Occupied units paying rent (excluding units where GRAPI cannot be computed)!!30.0 to 34.9 percent,Estimate!!GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME (GRAPI)!!Occupied units paying rent (excluding units where GRAPI cannot be computed)!!35.0 percent or more,Percent Estimate!!GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME (GRAPI)!!Occupied units paying rent (excluding units where GRAPI cannot be computed)!!35.0 percent or more,Estimate!!GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME (GRAPI)!!Occupied units paying rent (excluding units where GRAPI cannot be computed)!!Not computed,Percent Estimate!!GROSS RENT AS A PERCENTAGE OF HOUSEHOLD INCOME (GRAPI)!!Occupied units paying rent (excluding units where GRAPI cannot be computed)!!Not computed
0,1400000US48085030100,"Census Tract 301, Collin County, Texas",2347,2347,2090,89.0,257,11.0,0.9,(X),...,57,24.6,25,10.8,9,3.9,67,28.9,115,(X)
1,1400000US48085030201,"Census Tract 302.01, Collin County, Texas",1157,1157,1122,97.0,35,3.0,0.0,(X),...,23,11.1,56,27.1,22,10.6,70,33.8,8,(X)
2,1400000US48085030202,"Census Tract 302.02, Collin County, Texas",1193,1193,1069,89.6,124,10.4,3.8,(X),...,8,14.8,2,3.7,24,44.4,7,13.0,53,(X)
3,1400000US48085030203,"Census Tract 302.03, Collin County, Texas",6216,6216,5993,96.4,223,3.6,1.0,(X),...,328,29.1,143,12.7,86,7.6,232,20.6,67,(X)
4,1400000US48085030301,"Census Tract 303.01, Collin County, Texas",2293,2293,2224,97.0,69,3.0,1.1,(X),...,13,3.7,40,11.4,9,2.6,210,60.0,53,(X)

In [0]:
house_ownership[["id","Geographic Area Name",
                 "Estimate!!VALUE!!Owner-occupied units",
                 "Estimate!!HOUSING OCCUPANCY!!Total housing units"]]

,id,Geographic Area Name,Estimate!!VALUE!!Owner-occupied units,Estimate!!HOUSING OCCUPANCY!!Total housing units
0,1400000US48085030100,"Census Tract 301, Collin County, Texas",1743,2347
1,1400000US48085030201,"Census Tract 302.01, Collin County, Texas",907,1157
2,1400000US48085030202,"Census Tract 302.02, Collin County, Texas",962,1193
3,1400000US48085030203,"Census Tract 302.03, Collin County, Texas",4799,6216
4,1400000US48085030301,"Census Tract 303.01, Collin County, Texas",1821,2293
...,...,...,...,...
1170,1400000US48439123300,"Census Tract 1233, Tarrant County, Texas",781,2466
1171,1400000US48439123400,"Census Tract 1234, Tarrant County, Texas",234,1132
1172,1400000US48439123500,"Census Tract 1235, Tarrant County, Texas",588,1119
1173,1400000US48439123600,"Census Tract 1236, Tarrant County, Texas",144,1231
1174,1400000US48439980000,"Census Tract 9800, Tarrant County, Texas",0,12

#### Creating column: House ownership rate

In [0]:
house_ownership["% house_ownership(housing_units)"]=house_ownership["Estimate!!VALUE!!Owner-occupied units"]/house_ownership["Estimate!!HOUSING OCCUPANCY!!Total housing units"]*100

In [0]:
house_ownership=house_ownership[["id","Geographic Area Name","% house_ownership(housing_units)",
                 "Estimate!!HOUSING OCCUPANCY!!Total housing units"
                ]].rename(columns={"Estimate!!HOUSING OCCUPANCY!!Total housing units":"Total_housing_units"})

In [0]:
house_ownership

,id,Geographic Area Name,% house_ownership(housing_units),Total_housing_units
0,1400000US48085030100,"Census Tract 301, Collin County, Texas",74.265019,2347
1,1400000US48085030201,"Census Tract 302.01, Collin County, Texas",78.392394,1157
2,1400000US48085030202,"Census Tract 302.02, Collin County, Texas",80.637049,1193
3,1400000US48085030203,"Census Tract 302.03, Collin County, Texas",77.203990,6216
4,1400000US48085030301,"Census Tract 303.01, Collin County, Texas",79.415613,2293
...,...,...,...,...
1170,1400000US48439123300,"Census Tract 1233, Tarrant County, Texas",31.670722,2466
1171,1400000US48439123400,"Census Tract 1234, Tarrant County, Texas",20.671378,1132
1172,1400000US48439123500,"Census Tract 1235, Tarrant County, Texas",52.546917,1119
1173,1400000US48439123600,"Census Tract 1236, Tarrant County, Texas",11.697807,1231
1174,1400000US48439980000,"Census Tract 9800, Tarrant County, Texas",0.000000,12

### 7. Public Assistance
Table B19057

In [0]:
public_assistance=pd.read_csv("ACSDT5Y2018.B19057_data_with_overlays_2020-04-19T062106.csv",header=1)

In [0]:
public_assistance=public_assistance[["id","Geographic Area Name","Estimate!!Total!!With public assistance income","Estimate!!Total"
                  ]].rename(columns={"Estimate!!Total!!With public assistance income":"households_with_public_assistance_income",
                                    "Estimate!!Total":"total_households"})

In [0]:
public_assistance

,id,Geographic Area Name,households_with_public_assistance_income,total_households
0,1400000US48085031625,"Census Tract 316.25, Collin County, Texas",0,1776
1,1400000US48085031633,"Census Tract 316.33, Collin County, Texas",11,1414
2,1400000US48085031636,"Census Tract 316.36, Collin County, Texas",0,2598
3,1400000US48085032008,"Census Tract 320.08, Collin County, Texas",0,1587
4,1400000US48085031505,"Census Tract 315.05, Collin County, Texas",33,2950
...,...,...,...,...
1170,1400000US48439114006,"Census Tract 1140.06, Tarrant County, Texas",37,2652
1171,1400000US48439101301,"Census Tract 1013.01, Tarrant County, Texas",41,1869
1172,1400000US48439104503,"Census Tract 1045.03, Tarrant County, Texas",13,795
1173,1400000US48439106101,"Census Tract 1061.01, Tarrant County, Texas",14,495
1174,1400000US48439100502,"Census Tract 1005.02, Tarrant County, Texas",0,2293

### 8. SNAP
Table S2201

In [0]:
snap=pd.read_csv("ACSST5Y2018.S2201_data_with_overlays_2020-04-19T062707.csv",header=1)

In [0]:
snap=snap[["id","Geographic Area Name","Estimate!!Households receiving food stamps/SNAP!!Households"
     ]].rename(columns={"Estimate!!Households receiving food stamps/SNAP!!Households":"households_recieving_SNAP"})

### Joining all the datasets

In [0]:
df_1=employment.merge(commute_df,on=["id","Geographic Area Name"],how='inner')

In [0]:
df_2=df_1.merge(fam_df,on=["id","Geographic Area Name"],how='inner')

In [0]:
df_3=df_2.merge(median_household,on=["id","Geographic Area Name"],how='inner')

In [0]:
df_4=df_3.merge(gini,on=["id","Geographic Area Name"],how='inner')

In [0]:
df_5=df_4.merge(house_ownership,on=["id","Geographic Area Name"],how='inner')

In [0]:
df_6=df_5.merge(public_assistance,on=["id","Geographic Area Name"],how='inner')

In [0]:
df_7=df_6.merge(snap,on=["id","Geographic Area Name"],how='inner')

### Final Dataset containing all columns

In [0]:
df_7.to_csv("Economic_Indicators_All_Counties.csv")